### PR TITLE
Refactor code and some modifications.

### PR DESCRIPTION
**Pull request by sumanthvrao**
This refactor makes it easier to deal with files and lesser length for home page. Achievements are now in new file which can be easily added on to. Unwanted images are deleted. Contact and unnecessary footer logo is removed. Common code is moved to separate file.

### CODE REVIEW

**Comment by aniketnk** [comment]
The CSS is broken when I tried checking out the pr. See sccreenshot.

Screenshot 1
screenshot

Screenshot 2 (whole page)
screenshot1

**Comment by sumanthvrao** [comment]
@aniketnk Did you start a http server?

**Comment by aniketnk** [comment]
@sumanthvrao, Yes, I did.
If you look at the Network logs, there's no CSS file being fetched. 
Screenshot

**Comment by sumanthvrao** [comment]
@aniketnk interesting. I may have deleted some files by mistake. Though why does it work on chrome?

**Comment by sumanthvrao** [comment]
@aniketnk Bit shabby, but problem seems to be gone now.

**Comment by sumanthvrao** [comment]
> *achievements

what a guy!

**Comment by aniketnk** [comment]
Looks good to me. Did you try testing it on other browsers? IE, Edge? 
In mobile view, the logo gets cut off. Any fixes for that?

**Comment by sumanthvrao** [comment]
I think there's an issue for this. I did not test it in IE. (on ubuntu here).
Can you do it if your free. Will merge with once I get an approval.

**Comment by aniketnk** [comment]
Can't test either. I'm on OSX.
@Karki23 Can you test?

**Comment by sumanthvrao** [comment]
Merged as `60f93b9eb952ff8f86a2b469962f9c62bf99f9be`.
Thanks @aniketnk for testing :)

**Pull request merged**
